### ISSUE TITLE
Demex not listed in https://defillama.com/derivatives

### ISSUE THREAD

**Issue by eugenelhj** [DefiLlama/dimension-adapters#1033]
Hello was directed here from this [Issue](https://github.com/DefiLlama/DefiLlama-Adapters/issues/8245) , Demex from Carbon chain is not listed in https://defillama.com/derivatives and i checked that Demex is already included in the code and the test seems to work fine. Pls advice , thanks!

**Comment by dtmkeng** [comment]
https://defillama.com/derivatives/demex list already
