### ISSUE TITLE
Limit of eth_getLogs exceeded 

### ISSUE THREAD

**Issue by rockfridrich** [DefiLlama/dimension-adapters#1216]
Dear, DeFiLama team

After recent refactoring that seems to improve performance of calculation, Zerion adapter stopped working. 
<img width="804" alt="Screenshot 2024-02-14 at 9 58 44 PM" src="https://github.com/DefiLlama/dimension-adapters/assets/4190988/481b7b7c-89af-44a4-8fb8-5f35c2ed8f1a">

Raising internal error with `getLogs` helper. Error: `Invalid eth_getLogs request. 'fromBlock'-'toBlock' range too large. Max range: 800`
<img width="1207" alt="Screenshot 2024-02-14 at 9 51 40 PM" src="https://github.com/DefiLlama/dimension-adapters/assets/4190988/a95c2a27-4f3b-4432-a766-0b75f325bd8b">

May you provide suggestion what is the best way to fix this given error comes from internal libraries?

**Comment by dtmkeng** [comment]
issue about data is not update is from our api we working it sorry about that
