### ISSUE TITLE
Defillama's Daily Volume Display Doesn't Match Our Real Trading Activity

### ISSUE THREAD

**Issue by ZkSwapFinance** [DefiLlama/dimension-adapters#1220]
Dear Defillama Team,

Defillama: https://defillama.com/protocol/zkswap-finance
Website: https://zkswap.finance/

We reviewed the data from the past few days and noticed a discrepancy between the reported volume and the actual figures. 

Specifically, yesterday our trading volume exceeded 8 million, whereas Defillama indicated only 500k. 

We have verified the accuracy of Defillama's code, and it appears to display the correct values. However, the website itself is showing incorrect information. 

Could you please assist us in re-evaluating this matter?

![defillama_vol](https://github.com/DefiLlama/dimension-adapters/assets/126151208/4e866728-7a24-4a70-81dd-b7a9ede9df3a)

![defillama_vol_web](https://github.com/DefiLlama/dimension-adapters/assets/126151208/99343138-7e84-4b69-80d8-a2c835c44c3d)

Looking forward to hearing your response,
Best Regards,
Ryan

**Comment by dtmkeng** [comment]
fixed 
<img width="794" alt="image" src="https://github.com/DefiLlama/dimension-adapters/assets/11234402/dae0dbac-504b-45ec-abbe-68e8fed6ce4f">

**Comment by ZkSwapFinance** [comment]
Thank you so much, very fast and reliable.
