### ISSUE TITLE
Can you help to check dexs/apollox ? Seems api throw error.

### ISSUE THREAD

**Issue by bryansniyve** [DefiLlama/dimension-adapters#1232]
dexs/apollox/index.ts
<img width="1377" alt="截屏2024-02-21 10 38 05" src="https://github.com/DefiLlama/dimension-adapters/assets/134277602/b98a3fbc-3ff5-4775-a560-ab6861aabe2e">

**Comment by dtmkeng** [comment]
https://defillama.com/derivatives/apx-finance ?

**Comment by dtmkeng** [comment]
<img width="1630" alt="image" src="https://github.com/DefiLlama/dimension-adapters/assets/11234402/7688b40e-2528-4884-b940-a65902513b39">
