### ISSUE TITLE
Chainlink CCIP Fees use v1.0 addresses which will be deprecated March 31st

### ISSUE THREAD

**Issue by cryptoenron** [DefiLlama/dimension-adapters#1326]
Most CCIP traffic has migrated from v1.0 to v1.2 in anticipation of deprecation so the listed fees are not accurate. Deprecation notice and updated addresses linked below.

https://docs.chain.link/ccip/supported-networks/v1_2_0/mainnet

**Comment by dtmkeng** [comment]
https://github.com/DefiLlama/dimension-adapters/pull/1453
