### ISSUE TITLE
ERROR: Use Adapter v2 format for new adapters

### ISSUE THREAD

**Issue by MaxwellBlock** [DefiLlama/dimension-adapters#1503]
What is adapter v2? Can no more new adapters be added to this repository?

**Comment by dtmkeng** [comment]
now new adapter should add `version:  2` like this
```
const adapter: SimpleAdapter = {
  version: 2,
  adapter: {
    [CHAIN.SOLANA]: {
      fetch: fetch,
      start: 0,
    },
  },
};
```
it collect today data prev v1 it collect yesterday
