### ISSUE TITLE
【No data】Can you help check Cellula? 

### ISSUE THREAD

**Issue by cellulalifegame** [DefiLlama/dimension-adapters#1562]
Cellula's page, no data.

This is Cellula's page: https://defillama.com/protocol/cellula#information

This is PR: https://github.com/DefiLlama/dimension-adapters/pull/1519

**Comment by cellulalifegame** [comment]
Hi @dtmkeng . 
can you help me? Cellula's page, no data.

**Comment by dtmkeng** [comment]
https://defillama.com/protocol/cellula?fees=true&revenue=true
