### ISSUE TITLE
Volume data is not being synchronised since 31 May. (Keller Finance V2)

### ISSUE THREAD

**Issue by 0xArata** [DefiLlama/dimension-adapters#1567]
![Screenshot 2024-06-07 at 17 19 01](https://github.com/DefiLlama/dimension-adapters/assets/92546123/607b462d-a61c-41e0-ad1a-15cf54df0b8a)
We have just noticed that since a week ago the volume data is not being displayed/synchronised. Can you help us with this? Thanks in advance

**Comment by dtmkeng** [comment]
fixed
