### ISSUE TITLE
Hi @dtmkeng

### ISSUE THREAD

**Issue by opensea0508** [DefiLlama/dimension-adapters#1656]
Hi @dtmkeng 
Can we change logo and name? from `Bitoro` to `Bitoro Network`?
This would be new logo. Much appreciated!
![btoro](https://github.com/DefiLlama/dimension-adapters/assets/104680124/b1062ffb-0ec3-4643-af81-ad295bef3524)

_Originally posted by @opensea0508 in https://github.com/DefiLlama/dimension-adapters/issues/1629#issuecomment-2210986951_

Refer: https://github.com/DefiLlama/dimension-adapters/issues/1654

**Comment by Define101** [comment]
Should be live within 2 hours
will close this issue
