### ISSUE TITLE
Seems like something error in our APX Finance Daily Volume chart

### ISSUE THREAD

**Issue by bryansniyve** [DefiLlama/dimension-adapters#1671]
Hello, seems like something error in our APX Finance Daily Volume chart, can you figure out that why the volume stay the same data during Jul 8, 2024 - Jul 13, 2024 ?
<img width="1486" alt="image" src="https://github.com/user-attachments/assets/ae263630-b166-4266-835c-1d29b027096e">

**Comment by langyoung** [comment]
Jul 14 - 15 's daily volume data were wrong again!

**Comment by dtmkeng** [comment]
do you have historical data seem apollox can't refill

**Comment by langyoung** [comment]
No...I don't.
Do you know what happened to apollox daily volume data?

**Comment by langyoung** [comment]
Our manager said: the historical data were exclude pancake, so they were not saved in our database. Just ignore it. 
The most important thing is what happened to apollox daily volume data? Can you fixed it?
<img width="414" alt="image" src="https://github.com/user-attachments/assets/4e1cd341-47e1-4ed8-98d2-7da0b98a08eb">

As I tried in local, sometimes result were normal as above pic, but sometimes(30% Probability) as below: 
<img width="761" alt="image" src="https://github.com/user-attachments/assets/fc614c68-c812-4c25-94a0-195191754821">

I've no idea whether this caused this issue, but I tried this request in command and browser both working well!
So please help us !

**Comment by dtmkeng** [comment]
i guess some time when i call to your API it error we collect one time per day will fix run houry

**Comment by langyoung** [comment]
So you can fix this, right?

**Comment by dtmkeng** [comment]
yes

**Comment by linn-jupiter** [comment]
@dtmkeng   For now, I recommend not to request the interface concurrently, pls help to optimize the mechanism, thanks very much!

**Comment by dtmkeng** [comment]
what do you mean ?

**Comment by bryansniyve** [comment]
Hello, after we reviewed our BE code, when call >=2 chains requests at the same time, api will throw 90800 error. BE told me to send request with some interval to resolve this. 
 So I pulled another PR https://github.com/DefiLlama/dimension-adapters/pull/1695 to solve this issue, please review , Thank you very much!
