### ISSUE TITLE
Again: Daily volume issue

### ISSUE THREAD

**Issue by opensea0508** [DefiLlama/dimension-adapters#1689]
@dtmkeng 
I have noticed a discrepancy again in the DefiLlama statistics for our [platform](https://defillama.com/derivatives-aggregator/bitoro-network). 
Yesterday's volume is reported as $9.12M, but the actual volume is only $3.02M. 

The [issue](https://github.com/DefiLlama/dimension-adapters/issues/1654#issuecomment-2228736880) raised previously has not been resolved. 

Additionally, there is no date where the volume figures align with our [internal stats](https://bitoro.network/stats) or [Dune Analytics](https://dune.com/bitoro_network/stats). I wonder why this kinda discrepancies still persist...

Could you please double-check this on your end?

Regards,

![image](https://github.com/user-attachments/assets/b061a8e8-aad1-438e-b930-85acfb37e9c1)

**Comment by dtmkeng** [comment]
fixed
