### ISSUE TITLE
Daily Volume Keeps Repeating With Same Data For Days

### ISSUE THREAD

**Issue by Dongminh1997** [DefiLlama/dimension-adapters#1742]
Hi, Our protocol Magpie has an error with daily volume. It kept repeating for several days like this and I saw some others were facing the same error too. Could you help us to fix it please?
![Capture](https://github.com/user-attachments/assets/988988a4-1fea-4b0c-bc1a-203b9bcccabe)

**Comment by Dongminh1997** [comment]
We didn't see any request to get daily data from your side since 31th last month to 2nd this month
![Capture (1)](https://github.com/user-attachments/assets/d57717b5-bbbb-4ade-8df5-70ccedb1af17)

**Comment by dtmkeng** [comment]
will take a look

**Comment by Dongminh1997** [comment]
@dtmkeng thank you. I just saw some of them have been fixed the last 2 days data have been updated with wrong data at the same time today not sure why. Thank you
