### ISSUE TITLE
Daily Volume Keeps Repeating

### ISSUE THREAD

**Issue by Dongminh1997** [DefiLlama/dimension-adapters#1759]
@dtmkeng Sorry could you please check data of day 6/7/8 Aug for Magpie Protocol please. It kept repeating again. Thank you
![Capture](https://github.com/user-attachments/assets/65cb8a7a-fdd1-40b1-b8e2-d46deb629a84)

**Comment by dtmkeng** [comment]
wil chech

**Comment by dtmkeng** [comment]
refilled will good next 2-3 hour

**Comment by Dongminh1997** [comment]
Thank you

**Comment by Dongminh1997** [comment]
Hi @dtmkeng, Could you please update the daily data for us  from 9th August up till now please? I'm so sorry for bothering you a lot, our server just got a bug in new endpoint I submitted few days ago. So sorry again for taking you a lot of time.

**Comment by dtmkeng** [comment]
okay will refill

**Comment by Dongminh1997** [comment]
Thank you so muchhh

**Comment by Dongminh1997** [comment]
![Capture](https://github.com/user-attachments/assets/53f427ba-4ee1-4e44-8f39-963c55042681)
Hi @dtmkeng I saw your system called our endpoint to get new daily data today successfully but not sure why it still keeps repeating the old data yesterday? Do you know the reason why and how can we fix this issue permanently? Thank you?
