### ISSUE TITLE
Daily volume issue and replace with New logo

### ISSUE THREAD

**Issue by opensea0508** [DefiLlama/dimension-adapters#1815]
Hi @dtmkeng 
I am from [Bitoro Network](https://bitoro.network/). We again undergo the daily volume issue for the yesterday. It should be $56m but same with previous day ($12.6m). Would you please check it out? Please check out stats and [dune](https://dune.com/bitoro_network/stats)

![image](https://github.com/user-attachments/assets/76ec4633-88e5-4ff5-a838-6f257b69d044)

**Comment by dtmkeng** [comment]
will take a look

**Comment by opensea0508** [comment]
It seems it got fixed. But our network detail wasn't updated. would you?

We excited to let you know what we have new logo. Would you kindly replace with this?
![bitoro](https://github.com/user-attachments/assets/e143cf6d-391c-4b7e-9e1b-cdd4735de791)

**Comment by opensea0508** [comment]
Hey @dtmkeng 
Wondering if you had a chance to check my last comment for replacing with our new logo.....

**Comment by Define101** [comment]
will be good within 2 hours @opensea0508

**Comment by opensea0508** [comment]
> will be good within 2 hours @opensea0508

yeah.. still same.. wondering if you forgot @Define101

**Comment by opensea0508** [comment]
Hello @Define101 @dtmkeng 
I'm not sure what's happening, but our new logo still isn't showing up. Sorry to keep asking, but could you please check it out as soon as possible?

**Comment by opensea0508** [comment]
> Hello @Define101 @dtmkeng I'm not sure what's happening, but our new logo still isn't showing up. Sorry to keep asking, but could you please check it out as soon as possible?

🙏

**Comment by opensea0508** [comment]
@Define101

**Comment by opensea0508** [comment]
Hey @Define101 
Yesterday our new logo shown up for a little while, but now it got backed to old again. Wondering if you are having any problems on this issue. It's been taking Two weeks to update. Please please update with new logo.

**Comment by opensea0508** [comment]
Yes. That's okay.

**Comment by opensea0508** [comment]
Hey @dtmkeng 
What's wrong with your side? Can you see the old logo on the [dashboard](https://defillama.com/derivatives-aggregator)?
