### ISSUE TITLE
Cumulative volume not showing on the options page list for Arrow Markets

### ISSUE THREAD

**Issue by TerrenceAddison** [DefiLlama/dimension-adapters#1873]
As seen in the image below, our total volume is not showing up in the options page 
![image](https://github.com/user-attachments/assets/7abe80f0-138c-442f-89de-8edffba3ec1c)
![image](https://github.com/user-attachments/assets/63853ea8-87a4-4d97-a02f-bced6f2cba90)

**Comment by dtmkeng** [comment]
it is `totalPremiumVolume` your adapter can't return not show
