### ISSUE TITLE
Fluid fees & revenue not tracked daily even though script works?

### ISSUE THREAD

**Issue by bergben** [DefiLlama/dimension-adapters#1891]
For Fluid, the data has big gaps in fees and revenue: https://defillama.com/protocol/fluid#fees-revenue

But the script works fine, see below execution with commented in code for totalFees and totalRevenue which goes all the way from backfill start until now
![image](https://github.com/user-attachments/assets/2144a8c1-7540-40c3-b0f3-96b64325f23b)

Note I configured an alchemy RPC in my env vars, had some struggles with public rpc endpoints on Arbitrum. But those issues are completely random and I think have nothing to do with code. 

Any ideas? And can we get the data back-filled again to fill the gaps? 

Btw. there seem to be gaps for other protocols too, e.g. Aave from July 27 to Aug 12, GMX some gaps since mid July

**Comment by dtmkeng** [comment]
will take a look

**Comment by dtmkeng** [comment]
fixed
