### ISSUE TITLE
derevaties volume for flash.trade does not update

### ISSUE THREAD

**Issue by UjjwalGupta49** [DefiLlama/dimension-adapters#1907]
Hi there, the derevaties volume for flash.trade is not being updated on DefiLama via the dimension adapters (https://defillama.com/protocol/flashtrade?derivativesVolume=true). We have the correct data to backfill the missing stats and would be helpful if you could to share updates on the issues currently being faced by the adapter for 24 hrours volume.

following up on my comments on this PR - https://github.com/DefiLlama/dimension-adapters/pull/1522#issuecomment-2162539350

**Comment by dtmkeng** [comment]
let me check

**Comment by dtmkeng** [comment]
seem your api is 403 when call from our server could  you check 
<img width="1652" alt="image" src="https://github.com/user-attachments/assets/06c067a8-6588-4b92-80d2-ae6ccbf144b8">

**Comment by UjjwalGupta49** [comment]
i see, can you please share your CIDR that we can use to whitelist your client.

**Comment by dtmkeng** [comment]
> i see, can you please share your CIDR that we can use to whitelist your client.

can't share

**Comment by UjjwalGupta49** [comment]
we've updated the API rules, can you please verify if you are able to make calls now?

**Comment by dtmkeng** [comment]
it work thanks

**Comment by UjjwalGupta49** [comment]
how can we backfill the missing data? We have the correct data from our API for the missing days.

**Comment by dtmkeng** [comment]
> how can we backfill the missing data? We have the correct data from our API for the missing days.

your api can't refill it refill just yesterday data
