### ISSUE TITLE
Inquiry regarding how the volume tracker works

### ISSUE THREAD

**Issue by TerrenceAddison** [DefiLlama/dimension-adapters#1947]
Hi, 

Checking in and wanted to inquire at what interval and what time do you guys make API calls to our endpoint to update volume? 
We're seeing some missing volumes that happened over 24 hours ago.

And what does the unix timestamp passed to the volume endpoint is supposed to represent?
E.g is the value passed supposed to be the start of the day? end of the day? or something else?

Thanks!

**Comment by dtmkeng** [comment]
run houry for collect data

**Comment by TerrenceAddison** [comment]
@dtmkeng 
Thanks, can you elaborate on what timestamp you are calling on an hourly basis or no params?
E.g:
if you're making a call at October 2nd 2024, 08:00 AM GMT
what unixtimestamp are passing to the API call?

and what are you trying to get as that unixtimestamp as params?
is it 24 hours before? 24 hours after? or something else?

Thanks!

**Comment by dtmkeng** [comment]
> @dtmkeng Thanks, can you elaborate on what timestamp you are calling on an hourly basis or no params? E.g: if you're making a call at October 2nd 2024, 08:00 AM GMT what unixtimestamp are passing to the API call?
> 
> and what are you trying to get as that unixtimestamp as params? is it 24 hours before? 24 hours after? or something else?
> 
> If you are not passing any unixtimestamp, what do you expect the returned value should be within what time range?
> 
> The reason I'm asking is because we're missing a lot of daily volume from our chart.
> 
> Thanks!

2 oct utc 0

**Comment by TerrenceAddison** [comment]
> > @dtmkeng Thanks, can you elaborate on what timestamp you are calling on an hourly basis or no params? E.g: if you're making a call at October 2nd 2024, 08:00 AM GMT what unixtimestamp are passing to the API call?
> > and what are you trying to get as that unixtimestamp as params? is it 24 hours before? 24 hours after? or something else?
> > If you are not passing any unixtimestamp, what do you expect the returned value should be within what time range?
> > The reason I'm asking is because we're missing a lot of daily volume from our chart.
> > Thanks!
> 
> 2 oct utc 0

so are you saying I should expect a call at
2 oct UTC 00:00 AM
2 oct UC 01:00 AM
2 oct UC 02:00 AM
2 oct UC 03:00 AM
and so on?

or:
2 oct UTC 00:00 AM
3 oct UTC 00:00 AM
4 oct UTC 00:00 AM

and are you guys passing unix timestamp as parameter?
if so what does the value represent? and what should I be returning to you guys? data before or after the unixtimestamp?

**Comment by dtmkeng** [comment]
know it call with utc 0 every time if use `options.startOfDay`

**Comment by TerrenceAddison** [comment]
> know it call with utc 0 every time if use `options.startOfDay`

okay so what should I be returning? 24 hours previous volume?

**Comment by dtmkeng** [comment]
> okay so what should I be returning? 24 hours previous volume?

that volume for range that dete since 0:00 till 23:59

**Comment by TerrenceAddison** [comment]
> > okay so what should I be returning? 24 hours previous volume?
> 
> that volume for range that dete since 0:00 till 23:59

okay I just want to confirm, so let's say you sent a query at Oct 2 UTC 00:00 AM

I should be giving you 
a. Oct 1 UTC 00:01 to Oct 2 UTC 23:59 PM
b. Oct 2 UTC 00:00 to Oct 2 UTC 23:59 PM

which one?

are you sending this unixtimestamp also as parameter or not? `1727827200`

**Comment by dtmkeng** [comment]
hi it better if you make api support start and end

**Comment by TerrenceAddison** [comment]
@dtmkeng Will do that once I have the bandwidth to update everything. Thanks for the reminder and answers!
