### ISSUE TITLE
Magpie Protocol

### ISSUE THREAD

**Issue by Dongminh1997** [DefiLlama/dimension-adapters#2165]
Hi, our protocol (https://defillama.com/aggregators/magpie-protocol) didn't update volume for yesterday (30/11/2024)
Could you check it please @dtmkeng 
![Screenshot 2024-12-02 161502](https://github.com/user-attachments/assets/967b95ff-df9b-4a37-a431-cab80934e2fe)

**Comment by Dongminh1997** [comment]
I saw you filled it but it was filled with result of 29th not 30th @dtmkeng

**Comment by dtmkeng** [comment]
thx

**Comment by Dongminh1997** [comment]
@dtmkeng could you check it again please? it was filled by 29th data not 30th data.

**Comment by dtmkeng** [comment]
will refill
