### ISSUE TITLE
The buffer adapter exports:

### ISSUE THREAD

**Issue by crystalshay2es** [DefiLlama/dimension-adapters#293]
The buffer adapter exports: 
        
 
 _______________________________________
    Fees for 22/2/2023
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 29/1/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1677110398
    Daily fees: 8807.019625
    Daily revenue: 8807.019625
    
    
    
    
    Done in 5.44s.

_Originally posted by @llamatester in https://github.com/DefiLlama/dimension-adapters/issues/265#issuecomment-1441546656_

**Comment by dtmkeng** [comment]
@crystalshay2es  ty for the report, i don't understand this issue, could you explain?
