### ISSUE TITLE
[Q] Replacing Anyswap's Stablecoins

### ISSUE THREAD

**Issue by ftm1337** [DefiLlama/dimension-adapters#664]
Recently, Multichain's (Anyswap) bridge collapsed and their tokens depegged to 1/15th of their previously perceived values.

Defillama uses a hard mapping on multiple chains that map mc's tokens like USDC or USDT to the real USDC or USDT on the Mainnet Ethereum. This results in a bugged calculation that inflates TVL, Volume, Fees, etc on these networks by upto 20x more in adapters that use offchain indexing like those that use their own subgraphs or custom APIs to feed data into DefiLlama.

A notable example is Fantom, where DAI is trading at 0.08, fUSDT at 0.13, USDC at 0.18 and so on.. The DEXes that use subgraphs are currently showing 5-15x more $ values in their TVL, Volume, Fees adapters.

Possible solution would be to identify other sources of stablecoin pricing and use that to calculate valuations. For example, on fantom, there are multiple native stablecoins like MIM & FRAX and multiple bridged tokens like axlUSDC that have been on the network since years and are still functioning properly, trading at $1.

I'm not sure about what and where we need to make the required changes in the DefiLlama repositories, so opening this thread in both repos (tvls & dimension).
One solution for Volume & Fees would be to use on-chain / event-based adapters like we have for solidly forks, but would be quite a bit laborious for 100s of projects..

edit:
On fantom, I noticed axlUSDC was showing up a price of $0, evident in adapters such as e3, equity, equalizer, spookyswap etc protocols that have majority usage of axlUSDC as primary stablecoin. (https://www.coingecko.com/en/coins/axelar-usdc)

**Comment by 0xngmi** [comment]
we set the price of all multichain assets to 0, although in some dexs these assets are priced by using the internal price against ftm

if you found a concrete case of mispricing related to this, could you point us to it?

**Comment by ftm1337** [comment]
@0xngmi here's what defillama volume (/dexs) board shows for fantom:
![image](https://github.com/DefiLlama/dimension-adapters/assets/84405345/a06b6a1a-a702-45e3-9fd4-a2c7d7295750)

(starting with the first one as example)
the adapter for spooky uses https://api.thegraph.com/subgraphs/name/eerieeight/spookyswap , running a simple query on it gives
![image](https://github.com/DefiLlama/dimension-adapters/assets/84405345/5913e159-eeda-4a56-8ce9-52b40e91d8d3)
which is what defillama shows. (the $5.28m volume for yesterday). 
if we compare it to other trackers, like gecko terminal
![Screenshot_2023-07-29 Top SpookySwap Pools by 24h Transaction GeckoTerminal](https://github.com/DefiLlama/dimension-adapters/assets/84405345/001669c0-93a0-4841-93c0-3e21c29874ea)
or dexscreener 
![image](https://github.com/DefiLlama/dimension-adapters/assets/84405345/20cef730-04d6-49ac-a67e-e5104329b54d)
or dextools
![image](https://github.com/DefiLlama/dimension-adapters/assets/84405345/144bfc34-e031-4ed8-8699-27e176136ded)

then we get  the number at around $1.1m,
and if we check the price of FTM, spooky's subgraph returns $1.29 = 1 FTM (i wish!) 
![image](https://github.com/DefiLlama/dimension-adapters/assets/84405345/f205b620-f2d9-4b2b-89dd-88c465b2bc1e)
the difference in prices is roughly the same 5x that USDC (multichain) has depegged to ($0.19 right now).

all of the other dexes that use subgraphs have similar issues.. with numbers being inflated about 5x. I'm not sure about wagmi's numbers though.. their site reports $30 while dexscreener says $25 (https://dexscreener.com/fantom/f:0xaf20f5f19698f1D19351028cd7103B63D30DE7d7)..  meanwhile, on defillama we see $3m+ .. i'm guessing its because of something related to its CL math not sitting well with depegged token's prices in the subgraph.. idk tbh.

i tried writing adapters that would iterate over the "Swap" events (similar to equalizer's adapter), but get with an out-of-memory heap error on my local machine when i do the `yarn test dexs spooky2`.. i guess its probably because of the millions of swaps that spooky has had coupled with the smol ram i have available. so maybe someone else can give it a shot..

**Comment by ftm1337** [comment]
It has got worse now.. over-reporting numbers by 10x with anyswap's USDC depegged to $0.1 :sweat_smile: 
![image](https://github.com/DefiLlama/dimension-adapters/assets/84405345/73b3e64f-2c46-4857-a418-5ad8885f0624)
for example, spooky should have 600K volume, instead of 6M
![image](https://github.com/DefiLlama/dimension-adapters/assets/84405345/321e3b72-92af-4df2-9afe-6527483abc28)

**Comment by 0xngmi** [comment]
sorry for lack of reply here, didnt see your messages

I've just pushed an update to most fantom dexs to price volume against FTM instead (and then we price FTM against coingecko). Haven't managed to match dexscreener volumes but dont see where the issue could be in our new methodology

As for wagmi, we'll completely delist it from fantom

**Comment by ftm1337** [comment]
thanks 0xngmi! the numbers look quite accurate now, similar to those reported at other sites. and the modified adapter is going to be quite useful if some other chain has a similar issue
there are still a few old ones with the wrong numbers on fantom.. i'll try to rewrite all those this week, and add the few missing ones (spirit v1, velocimeter)..
