### ISSUE TITLE
Polygon fees pulls from stale subgraph

### ISSUE THREAD

**Issue by 0xnirmal** [DefiLlama/dimension-adapters#689]
Wanted to flag that I think Polygon fees are off. Checked it with a few other sources (and an indexer I use) and results from subgraph are less than what I would expect.

https://github.com/DefiLlama/dimension-adapters/blob/master/fees/polygon.ts#L10

This subgraph relies on this [Quickswap pool to quote WMATIC-USDC](https://polygonscan.com/address/0x6e7a5fafcec6bb1e78bae2a1f0b612012bf14827), which seems like it may be quoting stale prices relative to mkt spot w/ more volume.

I reached out to @dmihal, but haven't heard back, figured I would also flag to you all as well.

**Comment by dtmkeng** [comment]
updated switch to query on chain data

**Comment by dtmkeng** [comment]
thank you for report
