### ISSUE TITLE
Uniswap Volume is 0 on OP Mainnet

### ISSUE THREAD

**Issue by MSilb7** [DefiLlama/dimension-adapters#784]
Uniswap Volume shows as 0 on OP Mainnet: https://defillama.com/dexs/chains/optimism

The subgraph returns an error for me ([raised here](https://github.com/Uniswap/v3-subgraph/issues/186)), but [Uniswap's info page](https://info.uniswap.org/#/optimism/) is working.

https://github.com/DefiLlama/dimension-adapters/blob/a2c167f2f7d71bc445b9d6722f45ae50c42cb74a/protocols/uniswap/index.ts#L23

**Comment by dtmkeng** [comment]
thank you report i update and refill data
